'use strict';

(function () {
  var ESC_KEYCODE = 27;
  var ENTER_KEYCODE = 13;
  var MULTIPLIER_DIVISOR_ON_HUNDRED_PARTS = 100;
  var MAX_PERCENT_INPUT_VALUE = 100;

  window.constants = {
    ESC_KEYCODE: ESC_KEYCODE,
    ENTER_KEYCODE: ENTER_KEYCODE,
    MULTIPLIER_DIVISOR_ON_HUNDRED_PARTS: MULTIPLIER_DIVISOR_ON_HUNDRED_PARTS,
    MAX_PERCENT_INPUT_VALUE: MAX_PERCENT_INPUT_VALUE
  };
})();
